//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SMTHEntities : DbContext
    {
        public SMTHEntities()
            : base("name=SMTHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_ACCOUNT> TB_ACCOUNT { get; set; }
        public DbSet<TB_BLOG> TB_BLOG { get; set; }
        public DbSet<TB_CATEGORIES> TB_CATEGORIES { get; set; }
        public DbSet<TB_COSTTYPE> TB_COSTTYPE { get; set; }
        public DbSet<TB_PRODUCT> TB_PRODUCT { get; set; }
    
        public virtual int ADD_NEW_PRODUCT(Nullable<int> m_iBrandID, Nullable<int> m_iCategory, string strTitle, string strDesc, string coverImage, Nullable<int> m_iPrice, Nullable<byte> m_bPricetype, string strDocs)
        {
            var m_iBrandIDParameter = m_iBrandID.HasValue ?
                new ObjectParameter("m_iBrandID", m_iBrandID) :
                new ObjectParameter("m_iBrandID", typeof(int));
    
            var m_iCategoryParameter = m_iCategory.HasValue ?
                new ObjectParameter("m_iCategory", m_iCategory) :
                new ObjectParameter("m_iCategory", typeof(int));
    
            var strTitleParameter = strTitle != null ?
                new ObjectParameter("strTitle", strTitle) :
                new ObjectParameter("strTitle", typeof(string));
    
            var strDescParameter = strDesc != null ?
                new ObjectParameter("strDesc", strDesc) :
                new ObjectParameter("strDesc", typeof(string));
    
            var coverImageParameter = coverImage != null ?
                new ObjectParameter("CoverImage", coverImage) :
                new ObjectParameter("CoverImage", typeof(string));
    
            var m_iPriceParameter = m_iPrice.HasValue ?
                new ObjectParameter("m_iPrice", m_iPrice) :
                new ObjectParameter("m_iPrice", typeof(int));
    
            var m_bPricetypeParameter = m_bPricetype.HasValue ?
                new ObjectParameter("m_bPricetype", m_bPricetype) :
                new ObjectParameter("m_bPricetype", typeof(byte));
    
            var strDocsParameter = strDocs != null ?
                new ObjectParameter("strDocs", strDocs) :
                new ObjectParameter("strDocs", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_NEW_PRODUCT", m_iBrandIDParameter, m_iCategoryParameter, strTitleParameter, strDescParameter, coverImageParameter, m_iPriceParameter, m_bPricetypeParameter, strDocsParameter);
        }
    }
}
