//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ACCOUNT
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Passwd { get; set; }
        public byte m_bAuthority { get; set; }
        public string MailAdress { get; set; }
        public string PrivateKey { get; set; }
        public string Name { get; set; }
    }
}
