//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BLOG
    {
        public int ID { get; set; }
        public string strTile { get; set; }
        public string strDesc { get; set; }
        public int m_iSender { get; set; }
        public Nullable<System.DateTime> m_dtSendDate { get; set; }
    }
}
